management:
  health:
    redis:
      enabled: true

spring:
  cache:
    redis:
      cache-null-values: false
      time-to-live: 15m
      use-key-prefix: false
    type: redis
  data:
    redis:
      repositories:
        enabled: true
  redis:
    host: localhost
    port: 6379
